---
- name: Ensure dependencies are installed.
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - python3-debian
    state: present

- name: Ensure keyring directory exists
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Kubernetes ASCII key
  get_url:
    url: "{{ kubernetes_apt_repository }}/Release.key"
    dest: /tmp/kubernetes-release.key
    mode: '0644'

- name: Convert Kubernetes key to GPG binary format
  command: gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg /tmp/kubernetes-release.key
  args:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
- name: Add Kubernetes repository.
  deb822_repository:
    name: kubernetes
    types: deb
    uris: "{{ kubernetes_apt_repository }}"
    suites: /
    signed_by: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    enabled: true
  register: kubernetes_repository

- name: Update Apt cache.
  apt:
    update_cache: true
  when: kubernetes_repository.changed

- name: Add Kubernetes apt preferences file to pin a version.
  template:
    src: apt-preferences-kubernetes.j2
    dest: /etc/apt/preferences.d/kubernetes
    mode: 0644
